services:
  - type: web
    name: applit-web
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: REDIS_URL
        fromService:
          name: applit-redis
          type: redis
          property: connectionString

  - type: redis
    name: applit-redis
    plan: free
    ipAllowList: []

jobs:
  - name: applit-cron
    type: cron
    env: node
    schedule: "0 * * * *" # запуск каждый час
    buildCommand: "npm install"
    startCommand: "node worker.js"
    envVars:
      - key: REDIS_URL
        fromService:
          name: applit-redis
          type: redis
          property: connectionString
