services:
  - type: web
    name: applit-web
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: REDIS_URL
        fromService:
          name: applit-redis
          property: connectionString

  - type: worker
    name: applit-worker
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm run worker"
    envVars:
      - key: REDIS_URL
        fromService:
          name: applit-redis
          property: connectionString

  - type: redis
    name: applit-redis
    plan: free
    ipAllowList: []
